### ISSUE TITLE
Add VP9/webm support and allow audio codec selection

### ISSUE THREAD

**Issue by zfleeman** [zfleeman/ffmpeg4discord#17]
https://trac.ffmpeg.org/wiki/Encode/VP9

**Comment by zfleeman** [comment]
@RollingStar Do you have any suggestions for speeding up a vp9 encoding job? I'm trying with a lot of different parameters, but the speed is bumming me out.

When I had webm a while back, I used [this configuration](https://github.com/zfleeman/ffmpeg4discord/blob/fd0cabdf4c6e012db4d02d22ef609ab17ce832e7/discord.py#L92), and now I'm messing with various flags in my most [recent commit](https://github.com/zfleeman/ffmpeg4discord/commit/db65b7da4fe9b36e1eb6b9aef05cd7a620cbde50), and it's running at 0.2x at best. Well, I used `"deadline":"realtime"` and `"cpu-used":"8"`, and it processed at 2x speed, but the quality was just like x264, which I feel defeats the purpose.

Or should I just work towards adding it and warn people that it takes forever.

I _am_ writing this on my M2 MacBook, so maybe it will perform better on my Windows desktop. Would love to hear your thoughts.

**Comment by RollingStar** [comment]
I don't know a lot about vp9. 0.2x doesn't sound that bad to me for a newer encoder. Remember that h264 goes back to the early 2000s, this is a newer codec.

From my reading, vp9s alleged benefits are >1080p and (can't find a source for this) animation/games. I believe AV1 is a descendant of VP9 so you may be able to infer some benefits there.

> And for 1080p+ or grainy contents, VP9’s performance is close to HEVC. In certain conditions, VP9 performs even better than HEVC.

If I'm sharing a clip and trying to cram into the 25MB limit I might want to wait for a slow (ish) encode and get the max quality allowed in that size.

https://www.red5.net/blog/6-points-of-comparison-for-vp9-or-h265/

https://www.reddit.com/r/VP9/comments/9ivm98/useful_sources_for_getting_started_with_vp9/
