### ISSUE TITLE
Featrue request: Config output option

### ISSUE THREAD

**Issue by JustCauseWhyNot** [zfleeman/ffmpeg4discord#30]
The ability to set the output in the config file would be neat. Thank you.

**Comment by zfleeman** [comment]
Fixed with [this commit](https://github.com/zfleeman/ffmpeg4discord/commit/a01bfc5da25741e346c3385587cfa16c27b7a248). Will be merged with #31

**Comment by zfleeman** [comment]
let's leave it open until the PR is merged.

**Comment by JustCauseWhyNot** [comment]
Your call :saluting_face:
