### ISSUE TITLE
Output issues.

### ISSUE THREAD

**Issue by JustCauseWhyNot** [zfleeman/ffmpeg4discord#33]
I wanna be able to write a video by specifying it's title in the shell as an argument when I run the command. I know I was the one to say that specifying the path in the config would be nice, but I can't set the title on a per video basis. And if I remove the output command from the config, and try to specify one in the shell it doesn't work. If it could be possible to specify the title of the video with `-o _videorandom.web_` while having the directory it'll go to in the config that'd be nice.

This is certainly not a large issue. And I greatly appreciate the work you've put into this tool. It's been very handy.

**Comment by zfleeman** [comment]
I think I understand what you're asking. Do you want to be able to override fields in the config JSON with command line arguments? Right now, if you specify a config JSON, the program ignores the fields that would usually be set by arguments.

**Comment by JustCauseWhyNot** [comment]
Yea I am. And the problem is 2 part. I can't remove the option set in the config while specifying the config cause it'll fail with a the opt not being set. But if I set a directory I can't name the video title. You're understanding me correctly.

**Comment by zfleeman** [comment]
@JustCauseWhyNot I am pretty sure I addressed this concern with my latest release. Can you give it a shot?

**Comment by zfleeman** [comment]
Agh, dang! My test for this didn't include the new vp9 opts option. Shouldn't be a problem to fix it. I'll see if I can get a release made tonight.

**Comment by zfleeman** [comment]
@JustCauseWhyNot Can you try the latest test release? I think I've addressed this.

```
pip install -i https://test.pypi.org/simple/ --upgrade ffmpeg4discord
```

**Comment by JustCauseWhyNot** [comment]
It's working now. Thank you, and I can now set the output in the command argument.

**Comment by zfleeman** [comment]
@JustCauseWhyNot Awesome. I'll create a new release for PyPI. Also, you only need to supply options in the JSON config if they differ from the default value, now. And for frame rate, if you leave it blank/omit it from the JSON, it will just use the clip's input frame rate as the output frame rate -- no need to specify 60 if your input is 60.
